-- MySQL Script generated by MySQL Workbench
-- Sun Dec 22 11:52:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stylish
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stylish
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stylish` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `stylish` ;

-- -----------------------------------------------------
-- Table `stylish`.`campaign_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stylish`.`campaign_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT(11) NULL DEFAULT NULL,
  `campaign_images` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `stylish`.`campaign_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stylish`.`campaign_product` (
  `product_id` INT(11) NOT NULL,
  `campaign_story` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `stylish`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stylish`.`product` (
  `id` VARCHAR(255) NOT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `price` INT(255) NULL DEFAULT NULL,
  `texture` VARCHAR(45) NULL DEFAULT NULL,
  `wash` VARCHAR(45) NULL DEFAULT NULL,
  `place` VARCHAR(45) NULL DEFAULT NULL,
  `note` VARCHAR(45) NULL DEFAULT NULL,
  `catagory` VARCHAR(45) NULL DEFAULT NULL,
  `story` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stylish`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stylish`.`color` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `color_code` VARCHAR(255) NULL DEFAULT NULL,
  `product_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_color_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_color_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `stylish`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stylish`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stylish`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` VARCHAR(255) NOT NULL,
  `images` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `fk_images_product1_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_images_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `stylish`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stylish`.`main_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stylish`.`main_image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` VARCHAR(255) NOT NULL,
  `main_image` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `fk_main_image_product_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_main_image_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `stylish`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stylish`.`order_user_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stylish`.`order_user_list` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `time` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 137
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `stylish`.`order_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stylish`.`order_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_user_list_order_id` INT(11) NOT NULL,
  `product_id` VARCHAR(45) NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `size` VARCHAR(45) NULL DEFAULT NULL,
  `qty` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_order_list_order_user_list1_idx` (`order_user_list_order_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_order_list_order_user_list1`
    FOREIGN KEY (`order_user_list_order_id`)
    REFERENCES `stylish`.`order_user_list` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `stylish`.`pay_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stylish`.`pay_list` (
  `order_id` INT(11) NOT NULL,
  `acquirer` VARCHAR(45) NULL DEFAULT NULL,
  `rec_trade_id` VARCHAR(45) NULL DEFAULT NULL,
  `bank_transaction_id` VARCHAR(45) NULL DEFAULT NULL,
  `card_identifier` VARCHAR(45) NULL DEFAULT NULL,
  `merchant_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `stylish`.`signup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stylish`.`signup` (
  `id` VARCHAR(255) NOT NULL,
  `access_token` VARCHAR(45) NULL DEFAULT NULL,
  `access_expired` VARCHAR(45) NULL DEFAULT NULL,
  `provider` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `picture` VARCHAR(45) NULL DEFAULT NULL,
  `delayTime` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `stylish`.`total_price_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stylish`.`total_price_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_user_list_order_id` INT(11) NOT NULL,
  `subtotal` INT(11) NULL DEFAULT NULL,
  `freight` INT(11) NULL DEFAULT NULL,
  `total` INT(11) NULL DEFAULT NULL,
  INDEX `fk_total_price_list_order_user_list1_idx` (`order_user_list_order_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_total_price_list_order_user_list1`
    FOREIGN KEY (`order_user_list_order_id`)
    REFERENCES `stylish`.`order_user_list` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `stylish`.`variant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stylish`.`variant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` VARCHAR(255) NOT NULL,
  `color_code` VARCHAR(255) NULL DEFAULT NULL,
  `size` VARCHAR(45) NULL DEFAULT NULL,
  `stock` INT(255) NULL DEFAULT NULL,
  INDEX `fk_variant_product1_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_variant_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `stylish`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
